#!/bin/bash
cd ~

touch index.html

echo "<html><body><h1>Welcome to Web Server</h1></body></html>" > index.html

ls -l index.html


chmod 777 index.html

ls -l index.html


sudo chown www-data:www-data index.html

ls -l index.html


sudo chmod 755 index.html

ls -l index.html